### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by McDiod** [McDiod/TvT_BlackForestII.Chernarus#1]
- [x] Loadouts
- [x] Ausrüstung
- [x] Fahrzeuge
- [x] Ivan Base
- [x] Startlager
- [x] Fortifications für Fahrzeuge
- [x] Zivilbevölkerung
- [x] Wetter / Uhrzeit
- [x] replay
- [x] KI
- [x] Fahrzeug Paradrop 
  - todo: action, condition, vehicle types, start positions
- [x] respawn times
- [x] abschließendes npm Update
- [x] check fatigue settings
- [x] ody spezialwünsche
- [x] check spectator
- [ ] ggf. grad-fortifications build from vehicle deaktivieren
